### ISSUE TITLE
How to edit left navigation sidebar and create right sidebar?

### ISSUE THREAD

**Issue by namath** [dantman/monaco-port#3]
Sorry for taking your time for I am still new to php programming and managing my wiki. I have installed your monaco-port style for my MediaWiki ver 1.16. I've also applied the OutputPageBodyAttributes.patch and the ContentRightSidebar extension. Now my two issues are:
1. How do I add more links to the left navigation sidebar? I've tried to edit it in MediaWiki:Sidebar but was unsuccessful. Which php or css files do I need to look up in order to do this?
2. With the ContentRightSidebar extension installed, I am wondering how to make use of it but I am unsure of where to put the <right-sidebar> tag. If you can give me any pointers that would be really helpful.

Thank you,
Namath

**Comment by dantman** [comment]
Left sidebar is controlled using MediaWiki:Monaco-sidebar, there is also MediaWiki:Monaco-toolbox, these are the same messages Wikia used originally (however the #topusers# and category related extras don't work). You can look over the Monaco.i18n.php file for what i18n messages are defined. Or you could go to Special:AllMessages on your wiki and search for messages starting with 'monaco-' to get an overview.

<right-sidebar> is used in articles, the contents of the tag will be right floated in the page, and in Monaco they will be moved to the right sidebar. You can use <right-sidebar with-box title=msgname> to wrap it in a normal sidebar box. Note that in 1.16 you may need to use "withbox" instead of "with-box" since it seams like the parser may ignore attributes using a - in them. Additionally if you use <content>...</content> the right-sidebar will omit the additional markup and instead it will exclude the stuff outside of those content tags from what is put in the right sidebar.

You can see http://www.dragonballencyclopedia.com/wiki/Dragon_Ball_Encyclopedia and http://www.dragonballencyclopedia.com/wiki/Goku for examples and experiments with the tag.
